### ISSUE TITLE
Checking: is the project still active.

### ISSUE THREAD

**Issue by ramantehlan** [zviryatko/notifymi#1]
I tried running this project; for me, it didn't work. Is it functional?

**Comment by zviryatko** [comment]
Hello, I didn't work on it past year, but it should work, first of all it requires sudi, because I didn't figured out how to tell PAM to bypass, as second couple of libraries still requires, I will test it again and provide you more info how to run. And currently it can only pair device and nothing more.

**Comment by ramantehlan** [comment]
I did notice the need for `Sudo`. I was able to pair it, but not able to access the services. 

Closing this issue, thank you for the update. :)
